# Generated by Django 6.0.4 on 2026-05-04 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_student_address_remove_student_certificate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='allocated_course',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='is_allocated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='is_pending',
            field=models.BooleanField(default=False),
        ),
    ]
